# Generated by Django 3.2.12 on 2024-01-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20240120_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedconversion',
            name='original_extension',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supportedconversion',
            name='target_extension',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
