# Generated by Django 3.2.12 on 2024-01-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20240120_1723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supportedconversion',
            unique_together={('original_extension', 'target_extension'), ('original_mimetype', 'target_mimetype')},
        ),
    ]
