# Generated by Django 5.0.6 on 2024-09-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_documentconversion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentconversion',
            name='user',
        ),
    ]
