# Generated by Django 5.0.6 on 2024-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_documentconversion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='media/help_request_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
