# Generated by Django 5.0.6 on 2024-09-14 12:42

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_helprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentconversion',
            name='converted_file',
            field=models.FileField(default='image', storage=storages.backends.s3.S3Storage(), upload_to='media/converted_files/'),
        ),
        migrations.AlterField(
            model_name='documentconversion',
            name='original_file',
            field=models.FileField(default='default', storage=storages.backends.s3.S3Storage(), upload_to='media/uploaded_files/'),
        ),
    ]
