# Generated by Django 5.0.6 on 2024-10-07 17:41

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_documentconversion_converted_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentconversion',
            name='converted_file',
            field=models.FileField(default='default', storage=storages.backends.s3.S3Storage(), upload_to='media/converted_files/'),
        ),
        migrations.AlterField(
            model_name='documentconversion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_conversions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
