# Generated by Django 5.0.6 on 2025-07-26 11:36

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_alter_documentconversion_converted_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportedconversion",
            name="ocr_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="media/help_request_attachments/",
            ),
        ),
    ]
